all:
  hosts:
    webservers:
      ansible_host: 18.216.120.176
      ansible_user: ec2-user
      ansible_ssh_private_key_file: ../webserver-key.pem

    dbservers:
      ansible_host: 3.144.239.38
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ../dbserver-key.pem

  children: 
    debian_hosts:
      hosts:
        dbservers:
    redhat_hosts:
      hosts:
        webservers:
