---

all:
  hosts:
    wb01:
      ansible_host: 3.23.128.103
      ansible_user: ec2-user
      ansible_ssh_private_key_file: linux-server.pem
    wb02:
      ansible_host: 18.116.48.41
      ansible_user: ec2-user
      ansible_ssh_private_key_file: /linux-server.pem
    wb03:
      ansible_host: 3.142.92.88
      ansible_user: ec2-user
      ansible_ssh_private_key_file: ./linux-server.pem
